server:
  port: 9300
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://LagouCloudEurekaServerA:9200/eureka,http://LagouCloudEurekaServerB:9201/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: lagou-cloud-gateway
  #网关的配置
  cloud:
    gateway:
      routes: #配置路由
        - id: service-page-router
          #动态路由：从注册中心获取对应服务的实例
          uri: lb://lagou-service-page
          # uri: http://127.0.0.1:9100
          predicates:
            - Path=/page/**
        - id: service-product-router
          uri: lb://lagou-service-product
          # uri: http://127.0.0.1:9000
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1  #去掉uri中的第一部分，所以就要求我们通过网关访问的时候，把uri 的第一部分设置为product，从uri的第二部分开始才是真正的uri
