server:
  port: 9400
#注册到Eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:9200/eureka,http://LagouCloudEurekaServerB:9201/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:1.0-SNAPSHOT
spring:
  application:
    name: lagou-service-config
  cloud:
    config:
      server:
        #git配置：uri、用户名、密码、分支....
        git:
          uri: https://github.com/zhangzhengyang27/lagou-config.git  #配置git地址
          username: zhangzhengyang27
          password: yy093213
          search-paths:
            - lagou-config
      label: master
  rabbitmq:
    host: 121.40.77.89
    port: 5672
    username: zhangzhengyang
    password: 123456


#建议暴露所有的端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
